### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by siascone** [penghuidong520/PayMaZone#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

---

# MVP List
- [x] Should have 7 MVPs.
  - [x] 3 of those are User Auth, Heroku, and Production README.
  - [ ] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points

---

# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table’s name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State
- [x] State shape is flat!
- [ ] State’s keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
  - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [x] Top level slices
    - [x] `entities`
    - [x] `session`
    - [x] `errors` (here or in `ui`)
    - [x] `ui` (if needed)
  - [x] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can’t change
    + like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes
- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
  - [ ] Routes are displayed with `inline coding text` (backticks)

**Comment by siascone** [comment]
## Notes:
Please see the [Bluebird Wiki](https://github.com/appacademy/bluebird/wiki) for any references to notes

### Wiki Home Page
- Add a link place holder for your live link. 

### MVP List 
- Add estimated completion timelines/dates to each MVP
- Your features should be as follows:
  - Product Listings
  - Shopping Cart
  - Reviews/Ratings
  - Search
- Categories is a bonus feature along with lists and should not be included as one of your 4 features at this time.
- Your feature bullets should be written in a declarative way about what the user can example for products:
  - Users can view an index of product listings
  - Users can view individual product pages
  - etc.

### Database Schema
- looks good

### Sample State
- keys should be camelCased not snake_cased
- otherwise looks good

### Backend Routes
- your routes should have an API Endpoints heading
- you don't need the HTML section as rails handles this route for us. If you keep it the route should look like this 
  - `GET /` - `StaticPagesController#root`
- reducer your headings to h3s so that there is not a horizontal rule for each set of routes
- Your API Endpoint descriptions should be on the same line as the route and describe what the route returns in terms of data or what action it performs
  - Ex: `GET /api/items` - returns full list of  items
  - Ex: `POST /api/comments` - create a product review
- your comments routes should include your other CRUD actions (GET, PATCH, DELETE) 

### Frontend Routes
- components should be backticked
- `itemIndex` should have `itemIndexItem` nested within
  - consider renaming item to product so that you have `productIndex` and `productIndexItem` components or something similar
- your `cartIndex` should have `cartIndexItems` nested under it. These can potentially be a reuse of the `productIndexItem` component
- The comment/review route can go to the same component. You should include an edit route for the review edit form

**Comment by PedroKim** [comment]
### Sample State
- [x] `cart` and `review` slice of state should be pluralized
- [x] fix the indentation for `comments` slice of state

### Frontend Routes
- [x] update based off of Spencer's feedback

### Backend Routes
- [x] there is no consistency for each sub title for each routes information. Some are capitalized, some are singular form.

Let me know when you are done with these changes.

**Comment by penghuidong520** [comment]
Updated all wiki errors
